### ISSUE TITLE
Old save not loading the NEW version

### ISSUE THREAD

**Issue by Sasikaa** [ssblur/ParcelsAndPackages#3]
Sorry because put this crash report (minecraft client LOG copy-paste!!!)
I try loading the NEW version loading my old saving, and the save not loading, end the log is generate this (Try dowgrade old version, and working FINE!!):

[23:01:53] [Server thread/ERROR] [FML/]: A fatal exception occurred during the server starting event
java.lang.NullPointerException: remap target is null
	at net.minecraftforge.fml.common.event.FMLMissingMappingsEvent$MissingMapping.remap(FMLMissingMappingsEvent.java:114) ~[FMLMissingMappingsEvent$MissingMapping.class:?]
	at com.reimaginedgaming.blur.pandp.ParcelsAndPackagesMod.fixerer(ParcelsAndPackagesMod.java:64) ~[ParcelsAndPackagesMod.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_66]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560) ~[forge-1.8.9-11.15.0.1710-universal.jar:?]
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_66]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.fireMissingMappingEvent(Loader.java:944) ~[Loader.class:?]
	at net.minecraftforge.fml.common.registry.PersistentRegistryManager.injectSnapshot(PersistentRegistryManager.java:189) ~[PersistentRegistryManager.class:?]
	at net.minecraftforge.fml.common.FMLContainer.readData(FMLContainer.java:317) ~[FMLContainer.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.handleWorldDataLoad(FMLCommonHandler.java:408) ~[FMLCommonHandler.class:?]
	at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:116) ~[atm.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:81) ~[bpo.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:205) [bpo.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:441) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]

**Comment by ssblur** [comment]
Oh dear, terribly sorry about that. It appears that a remapping event executed improperly. Thank you for informing me, I will take care of this posthaste.

**Comment by ssblur** [comment]
I have fixed the issue and am uploading the fix to curseforge. Thank you for informing me of this.

**Comment by Sasikaa** [comment]
help you with pleasure
